version: '3.5'

services:
  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment: 
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    container_name: backend
  front-end:
    image: example-frontend
    ports:
      - 5000:5000
    environment: 
      - REACT_APP_BACKEND_URL=http://localhost:8080
    container_name: frontend
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
