FROM golang:1.16 AS build-env

WORKDIR /usr/src/app

ADD . /usr/src/app

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build -o goapp


FROM ubuntu
RUN apt update -y && apt install -y ca-certificates && rm -rf /var/cache/apt/*

WORKDIR /usr/src/app
COPY --from=build-env /usr/src/app/goapp /usr/src/app

RUN adduser --disabled-password appuser
USER appuser

EXPOSE 8080
CMD ["./goapp"]