FROM ubuntu:18.04

WORKDIR /usr/src/app

EXPOSE 5000

RUN apt update -y && \
    apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt install -y nodejs

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN useradd appuser && \
    npm install -g serve

COPY . .

RUN npm install && npm run build && \
    rm -rf src && rm -rf node_modules && rm -rf public

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]