FROM ubuntu:18.04 AS build

WORKDIR /usr/src/app

EXPOSE 5000

RUN apt update -y && \
    apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt install -y nodejs

ENV REACT_APP_BACKEND_URL=http://localhost:8080



COPY . .

RUN npm install && npm run build

FROM nginx:1.19-alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html

# RUN adduser --disabled-password appuser
# USER appuser