FROM golang:1.16 AS build

WORKDIR /usr/src/app

ADD . /usr/src/app

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build -o goapp

FROM alpine

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/goapp /usr/src/app

CMD [ "./goapp" ]